### ISSUE TITLE
Consider maintenance transfer

### ISSUE THREAD

**Issue by Antonio-Laguna** [postcss/postcss-media-minmax#39]
Hey @yisibl!

We've realised that this plugin, might need some spec compliance maintenance and potentially new features as it starts to get implemented in browsers. 

We've been moving most of the postcss plugins integrated within postcss-preset-env into the [CSSTools](https://github.com/csstools/postcss-plugins) mono repo to ease maintenance and keeping it updated ourselves since most weren't looked at for a while.

We were wondering if you're keen to transfer this repo to the org so we transfer and keep the history of contributions intact but is all integrated and heavily tested. We'd also keep the README in `zh`  😃

**Comment by yisibl** [comment]
Thank you for the invitation, but I am inclined to continue maintenance in this repository and I can add you as a member of this repository.

This is because the name and links to postcss-media-minmax are already widely available in various articles, Twitter and other social media. I don't want users who see these articles to be confused: "Why isn't the original repository maintained anymore? "

**Comment by Antonio-Laguna** [comment]
@yisibl thanks for answering so quickly! Given how postcss-preset-env got stuck with the PostCSS 8 migration we try to be careful with how we invest our time and efforts. We do understand that you would like to keep this plugin here.

To make sure postcss-preset-env doesn't get blocked we will fork this plugin so that we can work on it within the context of the mono repo. There we have more tools and checks in place that help with ensuring that quality is kept among plugins.

If we encounter bugs or issues we will submit patches here if that is ok?

**Comment by yisibl** [comment]
@Antonio-Laguna Okay, looking forward to your PR.
